### ISSUE TITLE
Entity 오류 수정

### ISSUE THREAD

**Issue by deingvelop** [team-coderder/Backend#11]
### 수정할 사항 1
`Group` Entity의 28째줄 `personalScheduleList` 부분에서 unknown target entity 오류 발생

```java
public class Group {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "group_id")
    private Long id;

    @Column(nullable = false)
    private String name;

    @OneToMany(mappedBy = "group") // 이 부분입니당
    private List<PersonalSchedule> personalSchedulesList;

    @OneToMany(mappedBy = "group")
    private List<GroupMembers> groupMembersList;
}
```

**Comment by deingvelop** [comment]
### 수정할 사항 2
`public class GroupMemberId` 옆에 `implements Serializable` 누락

**Comment by deingvelop** [comment]
### 수정할 사항 3
어노테이션 `@IdClass(GroupMemberId.class)` 누락

**Comment by deingvelop** [comment]
Group Entity에서만 발생하는 문제였으면 제가 혼자 해결하려 했지만, 다른 Entity들과도 함께 연관되는 부분이라 지연님이 아예 해결하고 develop에 merge해주시면 좋을 것 같습니다!

**Comment by deingvelop** [comment]
이 이슈로 branch 만들고 싶으시면 오른쪽에 Development - Create branch 클릭하시면 이 이슈로 브랜치 만들 수 있습니다!
아니면 그냥 현재 브랜치에서 해주셔도 되구 ㅎㅎ 해결되면 PR올리고 말씀해주세요~!

**Comment by JinJiyeon** [comment]
요청사항 반영해서 수정했고, feature-#11-modeling 브랜치로 pr 올렸뒀습니다
h2 db랑 연동해서 합의한 스키마대로 나오는 것으로 확인했는데요, 다른 이상 사항 발생하면 알려주세요!!
