### ISSUE TITLE
[Error] Error executing DDL 발생 - 해결 완료, ⭐피드백 필요

### ISSUE THREAD

**Issue by deingvelop** [team-coderder/Backend#24]
### 오류 내용

```
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "
    create table group (
       group_id  bigserial not null,
        name varchar(255) not null,
        primary key (group_id)
    )" via JDBC Statement
```

**Comment by deingvelop** [comment]
### 원인 분석

https://stackoverflow.com/questions/38299685/postgresql-hibernate-spring-auto-create-database

- PostgreSQL은 MySQL과는 다르게 `Create Database If not exist`을 지원하지는 않는다.

&nbsp; →    &nbsp; 따라서 auto-DDL을 실행하기 위해서는 아래와 같이 별도의 설정이 필요하다.


- 단, 실무에서 운영서버에서는 절대 Auto-DDL에 의지하지 않고, 개발이 아닌 배포용으로는 거의 절대 사용하지 않기 때문에 DB에 직접 테이블을 생성하는 것에 익숙해지도록 하자.

**Comment by deingvelop** [comment]
### 원인 분석 2

따라서 직접 PostgreSQL에 DB 테이블을 생성하고, SQL script로 접근해보려했지만 그런 relation은 존재하지 않는다는 오류만 떴다.

```error
[42P01] ERROR: relation "color-meeting.group" does not exist
```

<br>

이에 대한 원인을 찾아보니, 이 역시도 MySQL과 PostgreSQL의 차이점에 있었다.

- MySQL에서는 논리 Database를 schema 와 같은 의미로 사용
- 반면 PostgreSQL에서는 database와 schema 두가지 개념 모두 사용되며, database는 schema의 상위 개념
  - schema : table의 집합. 하나의 database를 논리적으로 나누는 개념

<br>

🖍 즉, MySQL에서의 **논리 database**는 **PostgreSQL에서의 schema**라고 할 수 있다.

> 이런 차이점 때문에 PostgreSQL에서는 하나의 DB instance에 있다해도 서로 다른 database에 있는 테이블 간에는 서로 JOIN 연산을 할 수 없다.
대신 서로 다른 schema의 테이블 간에는 JOIN 연산이 가능하다.

**Comment by deingvelop** [comment]
### 해결 시도

**application.properties**에서 DBC로 postgres에 연결할 때 스키마를 지정
```properties
# 예시 코드
jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema 
````


### 결과

해결 실패

```
SQL Error: 0, SQLState: 42601
ERROR: syntax error at or near "group"
HHH000327: Error performing load command
````
```
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
...
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "group"
  Position: 76
...
```

**Comment by deingvelop** [comment]
### 원인 분석 3

오류 로그를 보니, 다음과 같은 SQL 쿼리를 실행하는 데에 문제가 있었던 것을 알게 되었다.

```sql
select
    group0_.group_id as group_id1_0_0_,
    group0_.name as name2_0_0_
from
    group group0_ where
    group0_.group_id=1
```

- 실제로 스크립트로 실행시켜보니 같은 오류로 실행이 제대로 되지 않았다.

### 원인 파악
- `group`은 PostgreSQL에서 reserved word이기 때문에 무언가를 지시하는 용도(ex: 테이블명)로 사용될 수 없으며, 관련하여 에러가 발생한다.
- 따라서 identifier로 reserved word를 쓰기 위해서는 큰따옴표`"`를 통해 quote해서 사용해야 한다.

- 단, 일반적으로는 reserved word를 굳이 quoting해서 사용하는 것보다는 다른 이름을 사용하는 것이 바람직하다. Group이나 groups 등 다른 테이블명을 사용하는 방법도 있겠다.

**Comment by deingvelop** [comment]
### ⭐ 피드백 요청
`group`이 PostgreSQL의 reserved word인 이유로 에러가 나, 테이블명을 우선 임시로 `groups`로 변경하였습니다. 
그러나 복수형 네이밍도 사실 권장되지 않는다고 하니, 새로운 이름으로 바꿔서 아예 전반적으로 `group` 모델 관련 리팩토링을 하는 것도 좋을 듯 합니다.

우선 생각하고 있는 이름은 `team`이 있는데.. 다른 네이밍 아이디어 있으신지, 혹은 이대로 `group`으로 가도 좋은지 comment 남겨주시길 바랍니다
@JungguKang @JinJiyeon

**Comment by JinJiyeon** [comment]
대단하십니다..
team 좋아요!!

**Comment by deingvelop** [comment]
### 전달 사항

identifier에 특수문자를 제거하기 위해 default database 설정을 `color-meeting`에서 → `colormeeting`로 변경하고, 해당 DB에 테스트용 value를 몇 가지 삽입해두었습니다.

로컬 작업시 `application-db-url.properties`에 끝에 위치한 데이터베이스명  `/color-meeting`을 `/colormeeting`로 변경하여 진행하여주시길 바랍니다.
