### ISSUE TITLE
민진 - 1차 개발 마무리

### ISSUE THREAD

**Issue by deingvelop** [team-coderder/Backend#62]
- [x] Authentication 변경사항 적용
- [ ] 주요 비즈니스 로직에 대한 테스트 코드 작성
- [ ] Error Message 에서 stackTrace 등 필요 없는 사항 제거
- [ ] 정구의 코드리뷰 중 메소드 오류 수정

**Comment by deingvelop** [comment]
Error Message 에서 stackTrace 등 필요 없는 사항 제거 -> 디버깅 시도에도 우선 찾지 못함

- Security 구조를 다 뜯어봐야 할 것으로 보임

- 우선 Filter에서 상속받는 상위 추상 클래스가 예시와 다른 것이 원인으로 추정

**Comment by JinJiyeon** [comment]
Authentication 변경 사항 적용 후에도 제대로 작동하나요?
Security 갈고 난 다음에도 제대로 동작하는지 걱정되어서요.

**Comment by deingvelop** [comment]
@JinJiyeon 
오잉 답이 늦었네요
넵 확인해봤을 때는 제대로 작동합니다!
